---
- name: add ansible user to the nodes
  hosts: snapp
  gather_facts: no
  tasks:
    - name : make sure group wheel exists on the nodes 
      group: 
        name: wheel
        state: present

    - name: add user 
      user:
        name: ansible
        groups: wheel
        shell: /bin/bash
        append: yes

    - name: install sudo
      package:
        name: 
          - sudo
          - net-tools
          - iproute2
        state: latest
    - name: make ansible user passwordless   
      copy:
        content: " ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
        
